name: psycho_emotional_monitor
description: Minimal MVP app for monitoring a user's psycho-emotional state.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  http: any
  fl_chart: any
  google_fonts: any
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

